baseurl = "https://Ampny.github.io/Ampny.github.io/"
languageCode = "en-us"
title = "Anthony Fine: Online"
theme = "hugo-astatine-theme"

# main navbar links
[[menu.main]]
    name = "About Me"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/#projects"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3

# Site wide params
[params]
    authorName = "Anthony Fine"
    # Main image for the author
    [params.imgname]
        name = "img/site/headshot_cropped.png"
        alt = "Me!"

# Content
[permalinks]
    post = "/:slug/"
    page = "/:slug/"
